// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfpxjrjqddnmopybcjvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmcHhqcmpxZGRubW9weWJjanZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NTIxNDcsImV4cCI6MjA2NDEyODE0N30.3Jw4J18MaWydQzpXhiEDWHwGDaCXGupSkJ2wnmnzp0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);